!<<<<<<<<<<<<<<<<<<<<<<<<<<METODE DE NEWTON-RAPHSON>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
!OP OCT  2016

	SUBROUTINE NEWTONRAPHSON(X0,EPS,FUN,DFUN,NITER,IERR,XARREL)
	   IMPLICIT NONE
	   INTEGER IERR, NITER, MAXITER,J
	   PARAMETER (MAXITER=500)
!	   INTEGER N(MAXITER)
	   REAL*8 X0, EPS, FUN, DFUN, XARREL, DIF, xin
	   REAL*8 F0, DF0!, X(MAXITER)
!	   COMMON /VECTORS/ N,X
	   EXTERNAL FUN, DFUN
	   XIN=X0
	   IERR=1
25	   FORMAT(I8, 2X,F25.12)
10	   FORMAT('N=',I6,2X,'Sol.APROX: ',F25.12, 2X,'ERROR <',E20.1)
!5	   FORMAT(I6,2X,F25.12,2X,F25.12,2X,F25.12,2X,F25.12,2X,F25.12)

	   DO NITER=1, MAXITER
	     F0=FUN(X0)
	     DF0=DFUN(X0)
	     XARREL=X0-(F0/DF0)
		 DIF=DABS(XARREL-X0)
		 IF(XIN.EQ.2.54D0) THEN
		   WRITE(3,25) NITER, XARREL
		 ELSE IF(XIN.EQ.2.55D0) THEN
		   WRITE(4,25) NITER, XARREL
		 ELSE IF (XIN.EQ.2.7D0) THEN
		   WRITE(5,25) NITER, XARREL
		 ENDIF
!		 N(NITER)=NITER
!		 X(NITER)=XARREL
		 IF(DIF.LE.EPS) THEN
		   IERR=0
		   EXIT
		 ENDIF
		   X0=XARREL
	 ENDDO
15	   IF(IERR.EQ.0) THEN
	!	 WRITE(*,*) N,X
	     WRITE(*,10) NITER, XARREL, EPS
	     RETURN
	   ELSE
  		  WRITE(*,*)'El metode no ha convergit per x= ',XIN
	   ENDIF
	END
